import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/header";


export const metadata: Metadata = {
  title: "Beats Music",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased font-noto-sans bg-black text-white`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
